apiVersion: v1
kind: Secret
metadata:
  name: 'app-env-vars'
  namespace: {{ .Values.appName }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.appEnv.apiToken }}
  SECRET_TOKEN: {{ .Values.appEnv.secretToken }}
