apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: 3000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-env-vars
                  key: API_TOKEN
      imagePullSecrets:
        - name: registry-credentials
