apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ .Values.appName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
