apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: 80
